main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [

    # From Django Python Tutorial
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

    # Secondary Navbar
    path('home', views.HomeView.as_view()),
    path('about', views.AboutView.as_view()),
    path('contact', views.ContactView.as_view()),

    # Main Navigation
    #Principal Investigator | Teaching | Research | Service | Statement | Photos | Links
    path('principal-investigator', views.PrincipalInvestigatorView.as_view()),
    path('teaching', views.TeachingView.as_view()),
    path('research', views.ResearchView.as_view()),
    path('service', views.ServiceView.as_view()),
    path('statement', views.StatementView.as_view()),
    path('photos',views.PhotosView.as_view()),
    path('links',views.LinksView.as_view()),
]

neXtInstitute/urls.py
from django.contrib import admin # 
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]               









# Test push from Josh Patel

main/models.py
from django.db import models
from django.utils import timezone

import datetime

'''
default values below

TODO CHANGE TO A PUBLICATION MODEL LIST

'''
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self): 
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


# Create the model for person

class Person(models.Model):
    first_name = models.CharField(max_length=50, null=False)
    last_name = models.CharField(max_length=50, null=False)
    description = models.TextField(default="No Description Availiable")

main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, get_list_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.views.generic import TemplateView

from .models import Question, Choice

'''

DEFAULT

TO REPLACE WITH SEARCH RESULTS FOR PUBLICATIONS


'''

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request, 'DjangoTutorial/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'DjangoTutorial/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'DjangoTutorial/results.html', {'question': question})

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

#part 4
class IndexView(generic.ListView):
    template_name = 'DjangoTutorial/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte = timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'DjangoTutorial/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'DjangoTutorial/results.html'

# Secondary Navigation

class HomeView(TemplateView):
    template_name = "main-specific/home.html"

class AboutView(TemplateView):
    template_name = "main-specific/about.html"

class ContactView(TemplateView):
    template_name = "main-specific/contact.html"


# Main Navigation

# Views destined by Ramy
#Principal Investigator | Teaching | Research | Service | Statement | Photos | Links

class PrincipalInvestigatorView(TemplateView):
    template_name = 'main-specific/principal_investigator.html'

class TeachingView(TemplateView):
    template_name = 'main-specific/teaching.html'

class ResearchView(TemplateView):
    template_name = 'main-specific/research.html'

class ServiceView(TemplateView):
    template_name = 'main-specific/service.html'

class StatementView(TemplateView):
    template_name = 'main-specific/statement.html'

class PhotosView(TemplateView):
    template_name = 'main-specific/photos.html'

class LinksView(TemplateView):
    template_name = 'main-specific/links.html'

main/templates/DjangoTutorial/detail.html
<!doctype HTML>
<HTML>

<head>
  <title>DETAIL TITLE</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <!--    In case of error, show error message    -->
    {% if error_message %}
        <p>
            <strong>
                {{ error_message }}
            </strong>
        </p>
    {% endif %}

    <form action="{% url 'main:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="submit choice">
    </form>
</body>
</html>

main/templates/DjangoTutorial/html5-boilerplate.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
    </body>
</html>

main/templates/DjangoTutorial/index.html
<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% block content %}

<html>
<h1>Questions List</h1>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
            <a href="{% url 'main:detail' question.id %}">{{question.id}}. {{ question.question_text }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</HTML>

{% endblock content %}

main/templates/DjangoTutorial/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

main/templates/main-sitewide/base.html
{% comment %}

    TITLE: base.html
    AUTHOR: Lam Nguyen
    DATE: 2020-03-27
    DESCRIPTION:
        This is the base design, almost every single page should load from this.
        There are multiple sections below all organized in the following format.

{% endcomment %}

{% load static %}

<!doctype HTML>
<HTML>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <meta name="description" content="website description">
    <meta name="author" content="Lam Nguyen">
    <meta name="keywords" content="next, future factories, mechanical engineering, uofsc">
    <title>neXt Institute</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/b22242fa13.js" crossorigin="anonymous"></script>
    {% block links %}
        <!-- imported links go here -->
    {% endblock links %}
</head>
<body>
    <!-- titlebar.html is the titlebar -->
    {% include "main-sitewide/titlebar.html" %}

    <!-- navbar.html is the Navigation Bar -->
    {% include "main-sitewide/navbar.html" %} 

    {% block body %}
        replace this "block content"
    {% endblock body%}

    <!-- footer.html is the generic Footer -->
    {% include "main-sitewide/footer.html" %}
</body>
</HTML>

main/templates/main-sitewide/footer.html
{% comment %}

    TITLE: footer.html
    AUTHOR: Lam Nguyen
    DATE: 2020-03-27
    DESCRIPTION:
        This is the footer

{% endcomment %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/footer.css' %}">

<footer>
    <div class="footer">
        <div class="inner-footer">
            <div class="logo-container">
                <img src="{% static 'images/main-sitewide/neXt_logo.JPG' %}" alt="neXt Logo">
            </div>

            <div class="footer-third">
                <h1>Follow us</h1>
                <li><a><i class="fab fa-facebook-square"></i></a></li>
                <li><a><i class="fab fa-twitter-square"></i></a></li>
                <li><a><i class="fab fa-instagram-square"></i></a></li>
                <li><a><i class="fab fa-linkedin"></i></a></li>

                <span>
                    McNair Aerospace Center<br>
                    1000 Catawba st. #1084<br>
                    Columbia, SC 29210<br>
                    (803) 777-9596 <br>
                </span>
            </div>
            <div class="footer-third">
                <h1>More</h1>
                <li><a>Our Team</a></li>
                <li><a>Future Factories</a></li>
                <li><a>Composites</a></li>

            </div>
            <div class="footer-third">
                <h1>Need Help?</h1>
                <li><a>Terms and conditions</a></li>
                <li><a>Privacy Policy</a></li>
            </div>
        </div>
    </div>
</footer>

main/templates/main-sitewide/navbar.html
{% comment %}
    this is the Navbar file, edit here for changing sitewide Navigation bar


    TITLE: navbar.html
    AUTHOR: Lam Nguyen
    DATE: 2020-03-27
    DESCRIPTION: 
        This is meant to be placed below the titlebar, to be shown sitewide

{% endcomment %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/mainNavigation.css' %}">

<nav>
    <div class="main-navigation-container">
        <div class="main-navigation-container-inner">
            <ul class="main-navigation">
                <!-- Principal Investigator | Teaching | Research | Service | Statement | Photos | Links -->
                <a href="principal-investigator"><li>Principal Investigator</li></a>
                <a href="teaching"><li>Teaching</li></a>
                <a href="research"><li>Research</li></a>
                <a href="service"><li>Service</li></a>
                <a href="statement"><li>Statement</li></a>
                <a href="photos"><li>Photos</li></a>
                <a href="links"><li>Links</li></a>
            </ul>
        </div main-navigation-container-inner>
    </div main-navigation-container>
</nav>

main/templates/main-sitewide/titlebar.html
{% comment %}

    TITLE: titlebar.html
    AUTHOR: Lam Nguyen
    DATE: 2020-03-27
    DESCRIPTION:
        This is the titlebar, shows the logo and the secondary navbar

{% endcomment %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/titlebar.css' %}">

<header>
    <div class="header">
        <div class="inner-header">
            <div class="logo-container">
                <a href="home"><h1>neXt<span> Institute </span></h1><a>
            </div>

            <ul class="basic-navigation">
                <a href="home"><li>Home</li></a>
                <a href="about"><li>About us</li></a>
                <a href="contact"><li>Contact us</li></a>
            </ul>
        </div>
    </div>
</header>

main/templates/main-specific/AAA main-specific boilerplate.html
{% comment %}
    This is the boilerplate for the following main specific pages

    TITLE:
    AUTHOR:
    DATE:
    DESCRIPTION:

{% endcomment %}

<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% block content %}

<HTML>

<body>
    REPLACE THIS
</body>

</HTML>
{% endblock content %}

main/templates/main-specific/about.html
<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% load static %}

{% block links %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/introBanner.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/main-specific/about.css' %}">

{% endblock links %}

{% block body %}

<HTML>

<body>
    <!-- Banner -->
    <div class="intro-banner img-cont">
        <img class="object-fit_cover" src="{% static 'images/main-sitewide/example9.jpeg' %}" alt="home-major-image-1">
        <div class="text-wrapper">
            <div class="inner-text-wrapper">
                <span>WE STRIVE TO FIND THE FUTURE</span>
            </div>
            <div class="inner-text-wrapper">
                <span>RAMY HARIK</span>
            </div>
        </div>
    </div>
    <h1>Meet the team</h1>
</body>

</HTML>
{% endblock body %}

main/templates/main-specific/contact.html
<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% load static %}

{% block links %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/introBanner.css' %}">

{% endblock links %}

{% block body %}

<HTML>

<body>
    <!-- Banner -->
    <div class="intro-banner img-cont">
        <img class="object-fit_contain" src="{% static 'images/main-specific/contactusbanner.png' %}" alt="home-major-image-1">
    </div>

</body>

</HTML>
{% endblock body %}

main/templates/main-specific/home.html
{% extends "main-sitewide/base.html" %}

{% comment %}

    TITLE: home.html
    AUTHOR: Lam Nguyen
    DATE: 2020-03-27
    DESCRIPTION:
        This is the home page, shown to the end user at the the base url ''

{% endcomment %}

<!doctype HTML>

{% load static %}

{% block links %}

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/introBanner.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/main-specific/home.css' %}">

{% endblock links %}


{% block body %}

<HTML>

<body>
    <!-- Banner -->
    <div class="intro-banner img-cont">
        <img class="object-fit_cover" src="{% static 'images/main-sitewide/example1.jpeg' %}" alt="home-major-image-1">
        <div class="text-wrapper">
            <div class="inner-text-wrapper">
                <span>LOREM IPSUM DOLOR</span><br/>
                <span>CONSECTATEUR ADIPISCING.</span>
            </div>
            <div class="inner-text-wrapper">
                <span>
                    Sed do eiusmod tempor incididunt ut labore 
                    et dolore magna aliqua. Ut enim ad minim veniam, 
                    quis nostrud exercitation ullamco laboris
                </span
            </div>
        </div>
    </div>
    <div class="body">
        Test body
        <!-- Perhaps this should be left empty -->
    </div>

</body>

</HTML>

{% endblock body %}

main/templates/main-specific/links.html
<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% load static %}

{% block body %}

<HTML>

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/introBanner.css' %}">

<body>
    <!-- Banner -->
    <div class="intro-banner img-cont">
        <img class="object-fit_cover" src="{% static 'images/main-sitewide/example2.jpeg' %}" alt="home-major-image-1">
    </div>

</body>

</HTML>
{% endblock body %}

main/templates/main-specific/photos.html
<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% load static %}

{% block content %}

<HTML>

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/introBanner.css' %}">

<body>
    <!-- Banner -->
    <div class="intro-banner img-cont">
        <img class="object-fit_cover" src="{% static 'images/main-sitewide/example3.jpeg' %}" alt="home-major-image-1">
    </div>
    
</body>


</HTML>
{% endblock content %}

main/templates/main-specific/principal_investigator.html
<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% load static %}

{% block body %}

<HTML>

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/introBanner.css' %}">

<body>
    <!-- Banner -->
    <div class="intro-banner img-cont">
        <img class="object-fit_cover" src="{% static 'images/main-sitewide/example4.jpeg' %}" alt="home-major-image-1">
    </div>
    
</body>

</HTML>
{% endblock body %}

main/templates/main-specific/research.html
<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% load static %}

{% block body %}

<HTML>

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/introBanner.css' %}">

<body>
    <!-- Banner -->
    <div class="intro-banner img-cont">
        <img class="object-fit_cover" src="{% static 'images/main-sitewide/example5.jpeg' %}" alt="home-major-image-1">
    </div>
    
</body>


</HTML>
{% endblock body %}

main/templates/main-specific/service.html
<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% load static %}

{% block body %}

<HTML>

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/introBanner.css' %}">

<body>
    <!-- Banner -->
    <div class="intro-banner img-cont">
        <img class="object-fit_cover" src="{% static 'images/main-sitewide/example6.jpeg' %}" alt="home-major-image-1">
    </div>
    
</body>

</HTML>
{% endblock body %}

main/templates/main-specific/statement.html
<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% load static %}

{% block body %}

<HTML>

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/introBanner.css' %}">

<body>
    <!-- Banner -->
    <div class="intro-banner img-cont">
        <img class="object-fit_cover" src="{% static 'images/main-sitewide/example7.jpeg' %}" alt="home-major-image-1">
    </div>
    
</body>


</HTML>
{% endblock body %}

main/templates/main-specific/teaching.html
<!doctype HTML>

{% extends "main-sitewide/base.html" %}

{% load static %}

{% block body %}

<HTML>

<link rel="stylesheet" type="text/css" href="{% static 'css/main-sitewide/introBanner.css' %}">

<body>
    <!-- Banner -->
    <div class="intro-banner img-cont">
        <img class="object-fit_cover" src="{% static 'images/main-sitewide/example8.jpeg' %}" alt="home-major-image-1">
    </div>
    
</body>


</HTML>
{% endblock body %}

main/templates/main/index.html
<!doctype HTML>

{% extends "main/base.html" %}

{% block content %}

<html>
<h1>Questions List</h1>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li>
            <a href="{% url 'main:detail' question.id %}">{{question.id}}. {{ question.question_text }}</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</HTML>

{% endblock content %}

main/templates/main/links.html
<!doctype HTML>

{% extends "main/base.html" %}

{% block content %}

<HTML>

<body>
    LINKS PAGE
</body>

</HTML>
{% endblock content %}

main/templates/main/photos.html
<!doctype HTML>

{% extends "main/base.html" %}

{% block content %}

<HTML>

<body>
    PHOTOS PAGE
</body>

</HTML>
{% endblock content %}

main/templates/main/principal_investigator.html
<!doctype HTML>

{% extends "main/base.html" %}

{% block content %}

<HTML>

<body>
    PRINCIPAL INVESTIGATOR PAGE
</body>

</HTML>
{% endblock content %}

main/templates/main/research.html
<!doctype HTML>

{% extends "main/base.html" %}

{% block content %}

<HTML>

<body>
    RESEARCH PAGE
</body>

</HTML>
{% endblock content %}

main/templates/main/service.html
<!doctype HTML>

{% extends "main/base.html" %}

{% block content %}

<HTML>

<body>
    SERVICE PAGE
</body>

</HTML>
{% endblock content %}

main/templates/main/statement.html
<!doctype HTML>

{% extends "main/base.html" %}

{% block content %}

<HTML>

<body>
    STATEMENT PAGE
</body>

</HTML>
{% endblock content %}

main/templates/main/teaching.html
<!doctype HTML>

{% extends "main/base.html" %}

{% block content %}

<HTML>

<body>
    TEACHING PAGE
</body>

</HTML>
{% endblock content %}